// Technology marks for the Skills section. The paths live in public/marks.svg, a sprite that is cached like
// an image and kept out of the JS bundle; here is only each mark's sprite id and brand colour.
// Source: simple-icons (CC0-1.0). Brand names and logos belong to their owners. Tools without a mark get a dot.

export const marks: Record<string, { id: string; hex: string }> = {
  "React": { id: 'react', hex: '61DAFB' },
  "Next.js": { id: 'nextdotjs', hex: '000000' },
  "TypeScript": { id: 'typescript', hex: '3178C6' },
  "JavaScript": { id: 'javascript', hex: 'F7DF1E' },
  "HTML5": { id: 'html5', hex: 'E34F26' },
  "CSS": { id: 'css', hex: '663399' },
  "Sass": { id: 'sass', hex: 'CC6699' },
  "Less": { id: 'less', hex: '1D365D' },
  "TanStack Query": { id: 'reactquery', hex: 'FF4154' },
  "Redux Toolkit": { id: 'redux', hex: '764ABC' },
  "React Hook Form": { id: 'reacthookform', hex: 'EC5990' },
  "Socket.io": { id: 'socketdotio', hex: '010101' },
  "Tailwind CSS": { id: 'tailwindcss', hex: '06B6D4' },
  "Ant Design": { id: 'antdesign', hex: '0170FE' },
  "Material UI": { id: 'mui', hex: '007FFF' },
  "shadcn/ui": { id: 'shadcnui', hex: '000000' },
  "Radix UI": { id: 'radixui', hex: '161618' },
  "Bootstrap": { id: 'bootstrap', hex: '7952B3' },
  "Jest": { id: 'jest', hex: 'C21325' },
  "React Testing Library": { id: 'testinglibrary', hex: 'E33332' },
  "ESLint": { id: 'eslint', hex: '4B32C3' },
  "Prettier": { id: 'prettier', hex: 'F7B93E' },
  "Git": { id: 'git', hex: 'F03C2E' },
  "GitHub": { id: 'github', hex: '181717' },
  "Vite": { id: 'vite', hex: '9135FF' },
  "Vercel": { id: 'vercel', hex: '000000' },
  "Firebase": { id: 'firebase', hex: 'DD2C00' },
  "Clerk": { id: 'clerk', hex: '6C47FF' },
  "Chrome DevTools": { id: 'googlechrome', hex: '4285F4' },
  "Figma": { id: 'figma', hex: 'F24E1E' },
  "Node.js": { id: 'nodedotjs', hex: '5FA04E' },
  "Express": { id: 'express', hex: '0A0A0A' },
  "MongoDB": { id: 'mongodb', hex: '47A248' },
  "Claude Code": { id: 'claude', hex: 'D97757' },
  "Cursor": { id: 'cursor', hex: '000000' },
  "GitHub Copilot": { id: 'githubcopilot', hex: '000000' },
};
